# Generated by Django 5.2.6 on 2025-09-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
