# Generated by Django 5.2.6 on 2025-09-10 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings_service", "0002_alter_borrowing_borrow_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ["actual_return_date", "expected_return_date"]},
        ),
    ]
